### ISSUE TITLE
Could I get your pre-trained tree autoencoder?

### ISSUE THREAD

**Issue by LTEnjoy** [aisecure/AdvCodec#1]
Hi! I'm trying to do attack on my victim model using your great method but I run into some problems-- it's a bit of troublesome to directly train my own tree autoencoder and I have to deal with it in a hurry. So I would be appreciable if you could send me your tree autoencoder model, and it would be much better if you could tell me how to attack my own bert victim model (I have saved models locally). Best wishes!

**Comment by boxin-wbx** [comment]
Hi,

Thanks for your interest in our work.

We have updated our README and provided our pre-trained Tree Autoencoder [here](https://drive.google.com/file/d/1gIILKNhE3H0heisgNVHbES3GKWos4w1K/view?usp=sharing). Please let me know if you have further questions.
